name: Java 8 Compilation for Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    
    - name: Download original .jars
      run: bash download.sh

    - name: Decompile jars
      run: bash decompile.sh

    - name: Apply patches to decompiled jars
      run: bash apply_patches.sh

    - name: Recompile server
      run: bash compile-server.sh

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./serverout/server.jar
        asset_name: server.jar
        asset_content_type: application/java-archive
