name: Java 8 Compilation for Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: Setup dos2unix
      run: sudo apt-get update && sudo apt-get install -y dos2unix
    
    - name: Download original .jars
      run: bash download.sh

    - name: Decompile jars
      run: bash decompile.sh

    - name: Apply patches to decompiled jars
      run: bash apply_patches.sh

    - name: Recompile server
      run: bash compile-server.sh

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: serverout/server.jar
        asset_name: server.jar
        asset_content_type: application/java-archive
